from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel

from config_manager import UserRole, get_config_manager
from condor.web.auth import create_jwt, get_current_user, redeem_login_token
from condor.web.models import LoginResponse, WebUser

router = APIRouter(tags=["auth"])


class TokenLoginRequest(BaseModel):
    token: str


@router.post("/auth/token-login", response_model=LoginResponse)
async def token_login(req: TokenLoginRequest):
    """Login using a one-time token generated by the /web Telegram command."""
    info = redeem_login_token(req.token)
    if info is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid or expired login token")

    user_id = info["user_id"]
    cm = get_config_manager()
    role = cm.get_user_role(user_id)

    if role not in (UserRole.USER, UserRole.ADMIN):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Access denied. Ask the admin to approve your account in Telegram.",
        )

    jwt_token = create_jwt(
        user_id=user_id,
        username=info.get("username", ""),
        first_name=info.get("first_name", ""),
        role=role.value,
    )

    user = WebUser(id=user_id, username=info.get("username", ""), first_name=info.get("first_name", ""), role=role.value)
    return LoginResponse(token=jwt_token, user=user)


@router.get("/auth/me", response_model=WebUser)
async def me(user: WebUser = Depends(get_current_user)):
    return user
