"""Routines API routes — discover, run, schedule, and view routine results.

Runs execute in the disposable worker subprocess (§7.2 — same containment
as the MCP path); schedules are the DURABLE cron schedules in
store/schedules.json (§5.4), not in-memory intervals.
"""

from __future__ import annotations

import inspect
import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel

from condor.reports import list_reports
from condor.routine_store import get_routine_store
from condor.web.auth import get_current_user
from condor.web.models import WebUser

log = logging.getLogger(__name__)
router = APIRouter(prefix="/routines", tags=["routines"])


# ── Request / Response Models ──


class RunRequest(BaseModel):
    routine_name: str
    config: dict = {}


class ScheduleRequest(BaseModel):
    routine_name: str
    config: dict = {}
    cron: str = ""
    tz: str = "UTC"


# ── Routes ──


@router.get("")
async def list_routines(user: WebUser = Depends(get_current_user)):
    """List all discovered routines with their fields."""
    store = get_routine_store()
    return store.list_routines()


@router.post("/run")
async def run_routine(
    body: RunRequest,
    user: WebUser = Depends(get_current_user),
):
    """Execute a one-shot routine in the disposable worker (hard timeout)."""
    from condor.routines_worker import run_routine_in_worker

    name = body.routine_name
    agent_slug = ""
    if "/" in name:
        agent_slug, name = name.split("/", 1)
    out = await run_routine_in_worker(name, body.config, agent_slug=agent_slug)
    if out.get("error"):
        raise HTTPException(422, out["error"])
    return out


@router.post("/schedule")
async def schedule_routine(
    body: ScheduleRequest,
    user: WebUser = Depends(get_current_user),
):
    """Create a durable cron schedule (store/schedules.json, §5.4)."""
    from condor.agents.scheduler import create_routine_schedule

    if not body.cron:
        raise HTTPException(422, "cron is required (5-field cron expression)")
    name = body.routine_name
    agent_slug = ""
    if "/" in name:
        agent_slug, name = name.split("/", 1)
    try:
        return create_routine_schedule(
            routine=name,
            agent_slug=agent_slug,
            config=body.config,
            cron=body.cron,
            tz=body.tz,
        )
    except Exception as e:
        raise HTTPException(422, f"could not schedule: {e}")


@router.get("/schedules")
async def list_schedules(user: WebUser = Depends(get_current_user)):
    """List durable routine schedules."""
    from condor.agents.scheduler import RoutineScheduleStore

    data = RoutineScheduleStore().load()
    return {
        "schedules": [
            {"schedule_id": sid, **entry} for sid, entry in sorted(data.items())
        ]
    }


@router.delete("/schedules/{schedule_id}")
async def unschedule(schedule_id: str, user: WebUser = Depends(get_current_user)):
    from condor.agents.scheduler import RoutineScheduleStore

    if not RoutineScheduleStore().remove(schedule_id):
        raise HTTPException(404, "Schedule not found")
    return {"removed": True}


@router.get("/options/{source}")
async def get_field_options(
    source: str,
    user: WebUser = Depends(get_current_user),
):
    """Return dynamic options for routine config fields.

    No dynamic sources remain after the Hummingbot removal (the only source
    was hb ``controller_configs``); kept so option-typed fields degrade
    gracefully in the dashboard.
    """
    return {"options": []}


@router.get("/{routine_name:path}/source")
async def get_routine_source(
    routine_name: str,
    user: WebUser = Depends(get_current_user),
):
    """Return the source code of a routine."""
    store = get_routine_store()
    all_routines = store._discover_all()
    routine = all_routines.get(routine_name)
    if not routine:
        raise HTTPException(404, "Routine not found")
    try:
        source_file = inspect.getfile(routine.run_fn)
        source_path = Path(source_file).resolve()
        routines_dir = Path("routines").resolve()
        if not str(source_path).startswith(str(routines_dir)):
            raise HTTPException(403, "Source not available")
        source = source_path.read_text()
        return {"filename": source_path.name, "source": source}
    except (TypeError, OSError) as e:
        raise HTTPException(404, f"Source not available: {e}")


@router.get("/{routine_name:path}/reports")
async def get_routine_reports(
    routine_name: str,
    limit: int = Query(50, ge=1, le=200),
    user: WebUser = Depends(get_current_user),
):
    """Get reports generated by a specific routine."""
    # Agent routines are prefixed (e.g. "agent_slug/routine_name") but reports
    # may be saved with just the base name. Match both.
    base_name = routine_name.split("/")[-1] if "/" in routine_name else routine_name
    reports, total = list_reports(search=base_name, limit=limit)
    # Filter to exact source_name match (full prefixed or base name)
    exact = [r for r in reports if r.get("source_name") in (routine_name, base_name)]
    return {"reports": exact, "total": len(exact)}
